import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import bannerImage_one from "../public/bannerImage_one.png"
import accpet from "../public/accpet.jpg"
import bestDashboard from "../public/bestDashboard.jpg"
import coinStack from "../public/coinStack.jpg"
import instantApproval from "../public/instantApproval.jpg"
import ultraFast from "../public/ultraFast.jpg"
import zeroFees from "../public/zeroFees.jpg"

import your_team_3 from "../public/your_team_3.jpg"
import your_team_1 from "../public/your_team_1.jpg"
import your_team_2 from "../public/your_team_2.jpg"

import visa from "../public/visa.jpg"
import masterCard from "../public/masterCard.png"
import yesBank from "../public/yesBank.jpg"
import timeIsMoney from "../public/timeIsMoney.jpg"

//For popup from 
import FormPopUp from '../components/FormPopUp'
import { useState } from 'react'



export default function Home() {

  let [buttonPopup, setButtonPopup] = useState(false)



  return (
    <>


      <Head>
        <title>Spark</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/A.png" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@200;400;600&display=swap" rel="stylesheet"></link>
      </Head>


      <main>
        <div className={styles.firstBanner}>
          <Image src={bannerImage_one} className={styles.sparkFirstBannerImage} />
          <div>
            <h1>Corporate cards for your fast growing startup</h1>

            <h4>Flat 1% cashback - More savings on every spend <br />
              Launching on Feb 1, 2023</h4>

            <p>Get early access by joining the waitlist</p>

            {/* <button className={styles.joinTheWaitListbutton} onClick={()=>window.location.href = "https://huip9wud888.typeform.com/to/bNQbwFMG"}>Join the waitlist</button> */}
            <button className={styles.joinTheWaitListbutton} onClick={() => setButtonPopup(true)}>Join the waitlist</button>


            <FormPopUp trigger={buttonPopup} setTrigger={setButtonPopup}>
              <div className={styles.popupContent}>

                <h1>Join the Waitlist now</h1>

                <div>
                  <label>Full Name</label>
                  <input type="text" />
                </div>

                <div>
                  <label>Mobile</label>
                  <input type="text" />
                </div>

                <div>
                  <label>Work Email</label>
                  <input type="email" />
                </div>

                <div>
                  <label>Company Name</label>
                  <input type="text" />
                </div>

              </div>

              <button className={styles.popupButton}>Submit</button>
            </FormPopUp>



          </div>
        </div>


        <div>
          <h1 className={styles.heading}>Card Features</h1>
          <div className={styles.featuresDiv}>
            <div>
              <Image src={ultraFast} />
              <h4>Ultra fast application process</h4>
              <p>You can complete sign up in 5 minutes flat</p>
            </div>
            <div>
              <Image src={instantApproval} />

              <h4>Instant approval</h4>
              <p>Get your card approved instantly and start spending</p>
            </div>
            <div>
              <Image src={coinStack} />

              <h4>Flat 1% cashback</h4>
              <p>Cashback on all spends without any limitations</p>
            </div>
            <div>
              <Image src={zeroFees} />

              <h4>Zero fees</h4>
              <p>Yeah, you heard it right. Free to sign up and use with no fees</p>
            </div>
            <div>
              <Image src={accpet} />

              <h4>100% acceptance</h4>
              <p>Our visa cards are accepted anywhere, be if online or offline</p>
            </div>
            <div>
              <Image src={bestDashboard} />

              <h4>Best Dashboard</h4>
              <p>All controls at your fingertips and very easy to use</p>
            </div>
          </div>
        </div>





        {/* ///////////Additional Features (also your Team div in CSS) ////////// */}

        <h1 className={styles.heading}>Additional Features</h1>

        <div className={styles.yourTeam}>


          {/* <div>
            <Image src={your_team_1} alt="" />
            <div>
              <h1>Unlimited cards</h1>
              <p>Get cards for your team members</p>
            </div>
          </div> */}

          <div>
            <div>

              <h1>Expense Management</h1>
              <p>Know where you are spending to bring in efficiency</p>
            </div>
            <Image src={your_team_2} alt="" />
          </div>


          <div>
            <Image src={your_team_3} alt="" />
            <div>
              <h1>Maximum Control</h1>
              <p>Change spending limits and lock/unlock cards</p>
            </div>
          </div>

          <button className={styles.joinTheWaitListbutton} onClick={() => setButtonPopup(true)}>Join the waitlist</button>
        </div>


        {/* /////////// Our Partner ///////// */}

        <div className={styles.ourPartners}>
          <h1>Our Partners</h1>
          <div>
            <Image src={visa} alt="" />
            <Image src={masterCard} alt="" />
            <Image src={yesBank} alt="" />
          </div>
        </div>


        <div className={styles.saveTimeSaveMoney}>
          <div>
            <h1>Time is Money, <span>Save both</span></h1>
            <button className={styles.joinTheWaitListbutton} onClick={() => setButtonPopup(true)}>Join the waitlist</button>
          </div>
          <Image src={timeIsMoney} alt="" />
        </div>





      </main>


    </>
  )
}
